### ISSUE TITLE
Don't create random_password resource if var.password is supplied

### ISSUE THREAD

**Issue by visit1985** [terraform-aws-modules/terraform-aws-rds-aurora#171]
Hi,

since this is its only usage

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/23fe3f1223b7f14faf4f9600b3707bd8c7f832fc/main.tf#L3

Can we create the random_password resource only if var.password is not supplied?

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/23fe3f1223b7f14faf4f9600b3707bd8c7f832fc/main.tf#L16-L21

**Comment by arjitj2** [comment]
+1, came here to report the same issue

**Comment by callaingit** [comment]
Ii think this could be fixed with the PR https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/158 created for https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/157

**Comment by antonbabenko** [comment]
[v3.0.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v3.0.0) has been just released where this is fixed.

**Comment by visit1985** [comment]
Maybe this helps to clarify my use-case:

```
data "aws_secretsmanager_secret_version" "rds" {
  secret_id = "rds-credentials-${var.environment_alias}"
}

module "rds" {
  version = "v3.0.0"
  source = "terraform-aws-modules/rds-aurora/aws"
  name = "rds-${var.environment_alias}"
  engine_version = "11.8"
  instance_type = "db.t3.medium"
  create_cluster = true
  replica_count = 1

  username = jsondecode(data.aws_secretsmanager_secret_version.rds.secret_string)["username"]
  password = jsondecode(data.aws_secretsmanager_secret_version.rds.secret_string)["password"]

  ...
}
```


@callaingit Unfortunately your PR does not solve this issue. The random_password resource is still generated when I provide the password as a module input parameter.

@antonbabenko Can you please reopen this issue?

**Comment by antonbabenko** [comment]
@visit1985 [v3.1.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v3.1.0) has been just released.
