### ISSUE TITLE
Incompatible parameter group change in version 7.4.0 (2022-09-07)

### ISSUE THREAD

**Issue by CasaSky** [terraform-aws-modules/terraform-aws-rds-aurora#319]
## Description

Broken changes after yesterdays upgrade. We were using the default db_cluster_parameter_group_name from aws. In the logs it shows that this parameter is set now equal to subnet group name

```
  ~ resource "aws_rds_cluster" "this" {
      ~ db_cluster_parameter_group_name     = "default.aurora-postgresql13" -> "abc-service-dev"
        id                                  = "abc-service-dev"
        tags                                = {}
        # (42 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
╷
│ Error: Failed to modify RDS Cluster (abc-service-dev): DBClusterParameterGroupNotFound: DBClusterParameterGroup not found: dunning-dev
│ 	status code: 404, request id: ************
│ 
│   with module.abc_service_db.module.aurora_postgres.aws_rds_cluster.this[0],
│   on .terraform/modules/abc_service_db.aurora_postgres/main.tf line 59, in resource "aws_rds_cluster" "this":
│   59: resource "aws_rds_cluster" "this" {
│ 
╵
Releasing state lock. This may take a few moments...



Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```
Any idea why this broken change is happening?!

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.4.1 :tada:

**Comment by CasaSky** [comment]
Thank you so much! I will remove the usage of hard coded version '7.3.0' tomorrow and double check it :).

**Comment by CasaSky** [comment]
It seems to be partially fixed, at least for the **aws_rds_cluster**, but the bug is also part of the **aws_rds_cluster_instance** resource. My fault, i didn't mentioned this also in the description.

**Comment by mcawilcox** [comment]
Can I add a me-too to this issue?

I tried deploying an AWS sample today that brought in v7.4.1 of this module this afternoon (from scratch, and with minimal configuration changes), and got these errors:

```
│ Error: creating RDS Cluster (source-db-aurora-postgresql) Instance (source-db-aurora-postgresql-one): DBParameterGroupNotFound: DBParameterGroup not found: source-db-aurora-postgresql
│       status code: 404, request id: 402398e2-f38e-4d27-86c9-35ed2836e718
│
│   with module.cluster_source_db.aws_rds_cluster_instance.this["one"],
│   on .terraform/modules/cluster_source_db/main.tf line 170, in resource "aws_rds_cluster_instance" "this":
│  170: resource "aws_rds_cluster_instance" "this" {
│
│ Error: creating RDS Cluster (target-db-aurora-postgresql) Instance (target-db-aurora-postgresql-one): DBParameterGroupNotFound: DBParameterGroup not found: target-db-aurora-postgresql
│       status code: 404, request id: dd9a6cf4-27a4-4952-9a9b-750e7a8b1517
│
│   with module.cluster_target_db.aws_rds_cluster_instance.this["one"],
│   on .terraform/modules/cluster_target_db/main.tf line 170, in resource "aws_rds_cluster_instance" "this":
│  170: resource "aws_rds_cluster_instance" "this" {
```

Neither module block sets the flag to create a parameter group, so ought to make use of the default.
Instead, we see the module attempt to re-use the value of the "name" variable.
 
I needed to specify v7.3.0 to get a working version.

**Comment by mcawilcox** [comment]
I just tested #321 in v7.4.2 ... All seems to work. Thanks...

**Comment by CasaSky** [comment]
I also can confirm the stability of the release [v7.5.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/compare/v7.5.0...v7.5.1). I appreciate your support!
